INVALID_TOKEN = 0
INVALID_TOKEN_MSG = "Invalid token"
INVALID_USERNAME = 1
INVALID_USERNAME_MSG = "Invalid username"
INVALID_PASSWORD = 2
INVALID_PASSWORD_MSG = "Invalid password"
INVALID_DOC_ID = 3
INVALID_DOC_ID_MSG = "Doc not found"